### ISSUE TITLE
F5tts not working with Duration Model on: please help

### ISSUE THREAD

**Issue by MJAnderson1** [JarodMica/audiobook_maker#108]
Everything works fine without the duration model but as soon as I enable it crashes, I have the correct version of torch, I tried both Bing AI and Chat Gpt but both tell me the same thing: 

"It looks like you're encountering an IndexError in your code, specifically in the apply_rotary_pos_emb function. This error occurs because the tensor freqs is being indexed with too many dimensions."

- This might as well be Hieroglyphs to me, please help 

Here's the Full error:

Fetching 4 files: 100%|██████████████████████████████████████████████████████████████████████████| 4/4 [00:00<?, ?it/s]

Size mismatch for transformer.text_embed.text_blocks.0.dwconv.weight: checkpoint torch.Size([512, 7, 1]), model torch.Size([512, 1, 7])

Size mismatch for transformer.text_embed.text_blocks.1.dwconv.weight: checkpoint torch.Size([512, 7, 1]), model torch.Size([512, 1, 7])

Size mismatch for transformer.input_embed.conv_pos_embed.conv1d.0.weight: checkpoint torch.Size([512, 31, 32]), model torch.Size([512, 32, 31])

Size mismatch for transformer.input_embed.conv_pos_embed.conv1d.2.weight: checkpoint torch.Size([512, 31, 32]), model torch.Size([512, 32, 31])
Load vocos from local path engines/f5tts/vocoders
K:\audiobook_maker\venv\Lib\site-packages\f5_tts\infer\utils_infer.py:101: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(model_path, map_location="cpu")

vocab :  K:\audiobook_maker\venv\Lib\site-packages\f5_tts\infer\examples\vocab.txt
tokenizer :  custom
model :  engines\f5tts\models\models--SWivid--F5-TTS\snapshots\4dcc16f297f2ff98a17b3726b16f5de5a5e45672\F5TTS_Base\model_1200000.safetensors

1.0
Converting audio...
Using custom reference text...
gen_text 0 Narration of rezero using text to speech, Marine edition
Generating audio in 1 batches...
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]Building prefix dict from the default dictionary ...
2024-12-06 02:44:41 | DEBUG | jieba | Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\gfox\AppData\Local\Temp\jieba.cache
2024-12-06 02:44:41 | DEBUG | jieba | Loading model from cache C:\Users\gfox\AppData\Local\Temp\jieba.cache
Loading model cost 0.896 seconds.
2024-12-06 02:44:41 | DEBUG | jieba | Loading model cost 0.896 seconds.
Prefix dict has been built successfully.
2024-12-06 02:44:41 | DEBUG | jieba | Prefix dict has been built successfully.
  0%|                                                                                            | 0/1 [00:01<?, ?it/s]
Error calling Python override of QThread::run(): Traceback (most recent call last):
  File "K:\audiobook_maker\src\controller.py", line 48, in run
    self.function(self.directory_path, self.is_continue, self.report_progress, self.sentence_generated_callback, self.should_stop)
  File "K:\audiobook_maker\src\model.py", line 288, in generate_audio_for_sentence_threaded
    audio_path = self.generate_audio_proxy(sentence, speaker_settings, s2s_validated)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\audiobook_maker\src\model.py", line 314, in generate_audio_proxy
    success = tts_engines.generate_audio(self.tts_engine, sentence, voice_parameters, tts_engine_name, audio_path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\audiobook_maker\src\tts_engines.py", line 39, in generate_audio
    return generate_with_f5tts(tts_engine, sentence, voice_parameters, audio_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\audiobook_maker\src\tts_engines.py", line 148, in generate_with_f5tts
    tts_engine.infer(
  File "K:\audiobook_maker\venv\Lib\site-packages\f5_tts\api.py", line 120, in infer
    wav, sr, spect = infer_process(
                     ^^^^^^^^^^^^^^
  File "K:\audiobook_maker\venv\Lib\site-packages\f5_tts\infer\utils_infer.py", line 438, in infer_process
    return infer_batch_process(
           ^^^^^^^^^^^^^^^^^^^^
  File "K:\audiobook_maker\venv\Lib\site-packages\f5_tts\infer\utils_infer.py", line 506, in infer_batch_process
    duration_in_sec = prediction_model(audio, text_list)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\audiobook_maker\venv\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\audiobook_maker\venv\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\audiobook_maker\venv\Lib\site-packages\f5_tts\model\modules.py", line 939, in forward
    x = self.transformer(inp, text=text)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\audiobook_maker\venv\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\audiobook_maker\venv\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\audiobook_maker\venv\Lib\site-packages\f5_tts\model\modules.py", line 849, in forward
    x = block(x, mask=mask, rope=rope)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\audiobook_maker\venv\Lib\site-packages\f5_tts\model\modules.py", line 777, in __call__
    attn_output = self.attn(x=norm, mask=mask, rope=rope)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\audiobook_maker\venv\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\audiobook_maker\venv\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\audiobook_maker\venv\Lib\site-packages\f5_tts\model\modules.py", line 403, in forward
    return self.processor(self, x, mask=mask, rope=rope)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\audiobook_maker\venv\Lib\site-packages\f5_tts\model\modules.py", line 432, in __call__
    query = apply_rotary_pos_emb(query, freqs, q_xpos_scale)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\audiobook_maker\venv\Lib\site-packages\torch\amp\autocast_mode.py", line 43, in decorate_autocast
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "K:\audiobook_maker\venv\Lib\site-packages\x_transformers\x_transformers.py", line 685, in apply_rotary_pos_emb
    freqs = freqs[:, -seq_len:, :]
            ~~~~~^^^^^^^^^^^^^^^^^
IndexError: too many indices for tensor of dimension 2

**Comment by AlpacaManAlpha** [comment]
Same Error here,

**Comment by MJAnderson1** [comment]
So, no one?

**Comment by JarodMica** [comment]
I thought I had replied here, but I've gotta look into it so sorry for any delays if you're running into issues.

On one side duration model is not as helpful as you might think, so running without ATM isn't much different.

**Comment by MJAnderson1** [comment]
Thanx for the reply. thought I really needed it will try a few runs and see what I get.

**Comment by JarodMica** [comment]
Going to close for now
