### ISSUE TITLE
Unable to load audio - ERRORZ WILL LEAVE IN THE ISSUE THANK YOU

### ISSUE THREAD

**Issue by TheMindExpansionNetwork** [JarodMica/audiobook_maker#17]
D:\TTS-ZONE\AUDIO_BOOK_MAKER\audiobook_maker\audiobook_maker_v1.0\audiobook_maker_v1.0>.\runtime\python.exe .\audio_book_app_2_0.py
2023-10-09 15:17:58 | INFO | rvc.configs.config | Found GPU NVIDIA GeForce RTX 4070
Calling API with sentence: <Narration of rezero using text to speech, Marine edition>
API response received with audio path: ./results//random//random_00010.wav
D:\TTS-ZONE\AUDIO_BOOK_MAKER\audiobook_maker\audiobook_maker_v1.0\audiobook_maker_v1.0\runtime\lib\site-packages\torch\_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
2023-10-09 15:18:20 | WARNING | rvc.infer.modules.vc.modules | Traceback (most recent call last):
  File "D:\TTS-ZONE\AUDIO_BOOK_MAKER\audiobook_maker\audiobook_maker_v1.0\audiobook_maker_v1.0\rvc\infer\lib\audio.py", line 54, in load_audio
    with open(file, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: './results//random//random_00010.wav'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\TTS-ZONE\AUDIO_BOOK_MAKER\audiobook_maker\audiobook_maker_v1.0\audiobook_maker_v1.0\rvc\infer\modules\vc\modules.py", line 171, in vc_single
    audio = load_audio(input_audio_path, 16000)
  File "D:\TTS-ZONE\AUDIO_BOOK_MAKER\audiobook_maker\audiobook_maker_v1.0\audiobook_maker_v1.0\rvc\infer\lib\audio.py", line 66, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: [Errno 2] No such file or directory: './results//random//random_00010.wav'

Traceback (most recent call last):
  File "D:\TTS-ZONE\AUDIO_BOOK_MAKER\audiobook_maker\audiobook_maker_v1.0\audiobook_maker_v1.0\audio_book_app_2_0.py", line 46, in run
    self.function(self.directory_path, self.report_progress)
  File "D:\TTS-ZONE\AUDIO_BOOK_MAKER\audiobook_maker\audiobook_maker_v1.0\audiobook_maker_v1.0\audio_book_app_2_0.py", line 753, in generate_audio_for_sentence_threaded
    audio_path = self.generate_audio(sentence)
  File "D:\TTS-ZONE\AUDIO_BOOK_MAKER\audiobook_maker\audiobook_maker_v1.0\audiobook_maker_v1.0\audio_book_app_2_0.py", line 797, in generate_audio
    audio_path = rvc_convert(model_path=voice_model_path,
  File "D:\TTS-ZONE\AUDIO_BOOK_MAKER\audiobook_maker\audiobook_maker_v1.0\audiobook_maker_v1.0\runtime\lib\site-packages\rvc_pipe\rvc_infer.py", line 124, in rvc_convert
    wavfile.write(output_file_path, tgt_sr, audio_opt)
  File "D:\TTS-ZONE\AUDIO_BOOK_MAKER\audiobook_maker\audiobook_maker_v1.0\audiobook_maker_v1.0\runtime\lib\site-packages\scipy\io\wavfile.py", line 772, in write
    dkind = data.dtype.kind
AttributeError: 'NoneType' object has no attribute 'dtype'

D:\TTS-ZONE\AUDIO_BOOK_MAKER\audiobook_maker\audiobook_maker_v1.0\audiobook_maker_v1.0>pause
Press any key to continue . . .

Not sure if it is t his 

delimiter : "\n"
emotion : "None"
custom_emotion : ""
voice_name : "random"
audio_file : ""
voice_chunks : 1
candidates : 1
seed : 0
samples : 4
iterations : 32
temperature : .3
diffusion_sampler: "P"
pause_size : 8
cvvp_weight : 0
top_p : 0.8
diffusion_temp : 1
length_penalty : 6
repetition_penalty : 6
conditioning_free_k : 2
experimental_flags : ["Half Precision", "Conditioning-Free"]

Please let me know if any help Is appreciated.

**Comment by viktorblack** [comment]
you need to change the result folder check out the full installation vid https://youtu.be/Z4wnF6W8l2Y?si=P6tl_HKbT-8qJfSf&t=668 i hope this helps

**Comment by JarodMica** [comment]
As viktor said above, make sure you change the path as shown in the video for the results area. You're running into an issue where it's referencing a relative path:
