### ISSUE TITLE
error with own pth

### ISSUE THREAD

**Issue by iwmo** [JarodMica/audiobook_maker#24]
Hi Jarod,

I'm getting an error after copying selecting my pth as voice model.

`F:\TTS\audiobook_maker_v1.0>.\runtime\python.exe .\audio_book_app_2_0.py
2023-10-23 21:37:33 | INFO | rvc.configs.config | Found GPU NVIDIA GeForce RTX 3060
Calling API with sentence: <Once when I was six years old I saw a magnificent picture in a book, called True Stories from Nature,about the primeval forest.>
API response received with audio path: F:\TTS/Joao//Joao_00000.wav
F:\TTS\audiobook_maker_v1.0\runtime\lib\site-packages\torch\_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
Traceback (most recent call last):
  File "F:\TTS\audiobook_maker_v1.0\audio_book_app_2_0.py", line 46, in run
    self.function(self.directory_path, self.report_progress)
  File "F:\TTS\audiobook_maker_v1.0\audio_book_app_2_0.py", line 753, in generate_audio_for_sentence_threaded
    audio_path = self.generate_audio(sentence)
  File "F:\TTS\audiobook_maker_v1.0\audio_book_app_2_0.py", line 797, in generate_audio
    audio_path = rvc_convert(model_path=voice_model_path,
  File "F:\TTS\audiobook_maker_v1.0\runtime\lib\site-packages\rvc_pipe\rvc_infer.py", line 121, in rvc_convert
    vc.get_vc(model_path)
  File "F:\TTS\audiobook_maker_v1.0\rvc\infer\modules\vc\modules.py", line 110, in get_vc
    self.tgt_sr = self.cpt["config"][-1]
TypeError: tuple indices must be integers or slices, not str`

if I use the default, everything runs fine but the files get saved with azasu, while the output folder still saves with my own sound.

Hope I described it clearly..

Many thanks for the efforts. All the rest works great.

**Comment by iwmo** [comment]
Managed to solve the problem.
I had generated my pth with tortoise.

Today I tried with RVC and it works like a charm.
Converting super fast.

Nice work
