### ISSUE TITLE
Error using own trained model. self.tgt_sr = self.cpt["config"][-1]

### ISSUE THREAD

**Issue by athos54** [JarodMica/audiobook_maker#26]
Hi there, good job :) 

I have a similar problem. I have trained a model as you show on this video https://www.youtube.com/watch?v=6sTsqSQYIzs&t=1140s

When train is finish, Im be able to use on ai-voice-cloning

![image](https://github.com/JarodMica/audiobook_maker/assets/9353145/c42b50bd-6d12-4e49-80ef-0a723723ce9e)

![image](https://github.com/JarodMica/audiobook_maker/assets/9353145/db461ade-3c13-4337-8e12-165be43ecc96)

I try to copy the model from ai-voice-cloning to audiobook_maker

![image](https://github.com/JarodMica/audiobook_maker/assets/9353145/84077903-4ba4-46c4-87c7-554b0e962988)

and then I have this error

```
2023-10-26 18:47:42 | INFO | rvc.configs.config | Found GPU NVIDIA GeForce RTX 3090
Calling API with sentence: <The story we are about to embark upon takes us into a world of unlimited possibilities and borderless dreams, where a child born in Albuquerque, New Mexico, in 1964, was destined to reshape the globe.>
API response received with audio path: E:\ai-voice-cloning\results\random/samantha//samantha_00030.wav
E:\audiobook_maker-1.0\venv\lib\site-packages\torch\_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
Traceback (most recent call last):
  File "E:\audiobook_maker-1.0\audio_book_app_2_0.py", line 29, in run
    self.function(self.directory_path, self.report_progress)
  File "E:\audiobook_maker-1.0\audio_book_app_2_0.py", line 644, in generate_audio_for_sentence_threaded
    audio_path = self.generate_audio(sentence)
  File "E:\audiobook_maker-1.0\audio_book_app_2_0.py", line 688, in generate_audio
    audio_path = rvc_convert(model_path=voice_model_path,
  File "E:\audiobook_maker-1.0\venv\lib\site-packages\rvc_pipe\rvc_infer.py", line 121, in rvc_convert
    vc.get_vc(model_path)
  File "E:\audiobook_maker-1.0\rvc\infer\modules\vc\modules.py", line 110, in get_vc
    self.tgt_sr = self.cpt["config"][-1]
KeyError: 'config'
```

I think I have the absolute path set correctly because with other model the audobook_maker works correctly

**Comment by athos54** [comment]
replied here https://github.com/JarodMica/audiobook_maker/issues/20
