### ISSUE TITLE
Ussing Totoise TTS 1.0 - installed Audiobook - didn't work - tried to use TTS itself the next day - doesn't work anymore 

### ISSUE THREAD

**Issue by Aliasthump** [JarodMica/audiobook_maker#32]
Windows - Nvidia 3050
I use my Tortoise almost every day. This workflow would have been advantageous. But it didn't work. I needed to out put VO this mornings, so I tried to open Tortoise. It's now giving me this error. Please help, I've got weekly deadlines.
BTW, I tried installing the TTS 2.0 with RVC, but it errored out. (error below)

C:\Tortoitis\ai-voice-cloning>call .\venv\Scripts\activate.bat
C:\Tortoitis\ai-voice-cloning\venv\lib\site-packages\torch\onnx\_internal\_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
Whisper detected
Traceback (most recent call last):
  File "C:\Tortoitis\ai-voice-cloning\src\utils.py", line 97, in <module>
    from vall_e.emb.qnt import encode as valle_quantize
ModuleNotFoundError: No module named 'vall_e'

Traceback (most recent call last):
  File "C:\Tortoitis\ai-voice-cloning\src\utils.py", line 117, in <module>
    import bark
ModuleNotFoundError: No module named 'bark'

!WARNING! Automatically deduced sample batch size returned 1.
!WARNING! Automatically deduced sample batch size returned 1.
Traceback (most recent call last):
  File "C:\Tortoitis\ai-voice-cloning\src\main.py", line 24, in <module>
    webui = setup_gradio()
  File "C:\Tortoitis\ai-voice-cloning\src\webui.py", line 357, in setup_gradio
    result_voices = get_voice_list(args.results_folder)
  File "C:\Tortoitis\ai-voice-cloning\src\utils.py", line 3111, in get_voice_list
    os.makedirs(dir, exist_ok=True)
  File "C:\Users\Aidan\AppData\Local\Programs\Python\Python39\lib\os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\Users\Aidan\AppData\Local\Programs\Python\Python39\lib\os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\Users\Aidan\AppData\Local\Programs\Python\Python39\lib\os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\Users\Aidan\AppData\Local\Programs\Python\Python39\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '"C:'
Press any key to continue . . .

Here is the TTS 2.0 error

Possible latent mismatch: click the "(Re)Compute Voice Latents" button and then try again. Error: The specified pointer resides on host memory and is not registered with any CUDA device.

**Comment by Lastofthefirst** [comment]
Any progress?
