### ISSUE TITLE
Not finding output wav file?

### ISSUE THREAD

**Issue by PrizeGotti** [JarodMica/audiobook_maker#34]
I'm really not sure why this is happening, as far as I can tell I have everything set up right, but I get the following error before the script exits;

`2024-02-06 15:35:43 | WARNING | rvc.infer.modules.vc.modules | Traceback (most recent call last):
  File "D:\audiobook_maker_v1.1\rvc\infer\lib\audio.py", line 54, in load_audio
    with open(file, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: './results//random//random_00015.wav'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\audiobook_maker_v1.1\rvc\infer\modules\vc\modules.py", line 171, in vc_single
    audio = load_audio(input_audio_path, 16000)
  File "D:\audiobook_maker_v1.1\rvc\infer\lib\audio.py", line 66, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: [Errno 2] No such file or directory: './results//random//random_00015.wav'

Traceback (most recent call last):
  File "D:\audiobook_maker_v1.1\audio_book_app_2_0.py", line 46, in run
    self.function(self.directory_path, self.report_progress)
  File "D:\audiobook_maker_v1.1\audio_book_app_2_0.py", line 752, in generate_audio_for_sentence_threaded
    audio_path = self.generate_audio(sentence)
  File "D:\audiobook_maker_v1.1\audio_book_app_2_0.py", line 796, in generate_audio
    audio_path = rvc_convert(model_path=voice_model_path,
  File "D:\audiobook_maker_v1.1\runtime\lib\site-packages\rvc_pipe\rvc_infer.py", line 124, in rvc_convert
    wavfile.write(output_file_path, tgt_sr, audio_opt)
  File "D:\audiobook_maker_v1.1\runtime\lib\site-packages\scipy\io\wavfile.py", line 772, in write
    dkind = data.dtype.kind
AttributeError: 'NoneType' object has no attribute 'dtype'`

I have checked "results/random/" folder for Tortoise, and the first line of the text file has been generated (in this instance "random_00015.wav", so it's clear the two scripts are communicating, just seems to be an issue when communicating the callback?

Anyone know what could be causing this?

**Comment by PrizeGotti** [comment]
Rewatched the video and missed that part about setting an absolute path in Tortoise. Everything working now.
