### ISSUE TITLE
Version 3 error not working on my side

### ISSUE THREAD

**Issue by michaeltran33** [JarodMica/audiobook_maker#50]
It does 1 line in text_small. saved in result, but nothing in audiobook.

from TTS
D:\AIVoice\ai-voice-cloning\venv\lib\site-packages\torchaudio\functional\functional.py:1371: UserWarning: "kaiser_window" resampling method name is being deprecated and replaced by "sinc_interp_kaiser" in the next release. The default behavior remains unchanged.
  warnings.warn(
Generation took 5.974964618682861 seconds, saved to 'D:\AIVoice\ai-voice-cloning\results/mike//mike_00001.wav'

from Ausiobook
Parameters being sent to Gradio app:
delimiter:

emotion: None
custom_emotion:
voice_name: mike
microphone_source: None
voice_chunks: 0
candidates: 1
seed: 0
samples: 2
iterations: 32
temperature: 0.3
diffusion_sampler: DDIM
pause_size: 8
cvvp_weight: 0
top_p: 0.8
diffusion_temp: 1
length_penalty: 6
repetition_penalty: 6
conditioning_free_k: 2
experimental_flags: ['Half Precision', 'Conditioning-Free']
2024-06-15 08:55:29 | INFO | httpx | HTTP Request: GET http://localhost:7860/heartbeat/fd175f8f-9cb6-4cfe-8de5-a97116b4bf3d "HTTP/1.1 404 Not Found"
2024-06-15 08:55:31 | INFO | httpx | HTTP Request: GET http://localhost:7860/heartbeat/fd175f8f-9cb6-4cfe-8de5-a97116b4bf3d "HTTP/1.1 404 Not Found"
2024-06-15 08:55:33 | INFO | httpx | HTTP Request: GET http://localhost:7860/heartbeat/fd175f8f-9cb6-4cfe-8de5-a97116b4bf3d "HTTP/1.1 404 Not Found"
2024-06-15 08:55:35 | INFO | httpx | HTTP Request: GET http://localhost:7860/heartbeat/fd175f8f-9cb6-4cfe-8de5-a97116b4bf3d "HTTP/1.1 404 Not Found"
2024-06-15 08:55:37 | INFO | httpx | HTTP Request: GET http://localhost:7860/heartbeat/fd175f8f-9cb6-4cfe-8de5-a97116b4bf3d "HTTP/1.1 404 Not Found"
2024-06-15 08:55:37 | INFO | httpx | HTTP Request: GET http://localhost:7860/file=C:%5CTemp%5C2f1ba58c67ccea4ff133f755704c29d14bce91f8%5Cmike_00000.wav "HTTP/1.1 200 OK"
Error: The 'data' field is missing in {'visible': False, 'value': None, '__type__': 'update'}, retrying... (1/3)
2024-06-15 08:55:39 | INFO | httpx | HTTP Request: GET http://localhost:7860/heartbeat/fd175f8f-9cb6-4cfe-8de5-a97116b4bf3d "HTTP/1.1 404 Not Found"
2024-06-15 08:55:41 | INFO | httpx | HTTP Request: GET http://localhost:7860/heartbeat/fd175f8f-9cb6-4cfe-8de5-a97116b4bf3d "HTTP/1.1 404 Not Found"
Error: [WinError 10061] No connection could be made because the target machine actively refused it, retrying... (2/3)
2024-06-15 08:55:43 | INFO | httpx | HTTP Request: GET http://localhost:7860/heartbeat/fd175f8f-9cb6-4cfe-8de5-a97116b4bf3d "HTTP/1.1 404 Not Found"
2024-06-15 08:55:45 | INFO | httpx | HTTP Request: GET http://localhost:7860/heartbeat/fd175f8f-9cb6-4cfe-8de5-a97116b4bf3d "HTTP/1.1 404 Not Found"
Error: [WinError 10061] No connection could be made because the target machine actively refused it, retrying... (3/3)
Traceback (most recent call last):
  File "D:\AIVoice\audiobook_maker_v3.0\audio_book_app.py", line 46, in run
    self.function(self.directory_path, self.report_progress)
  File "D:\AIVoice\audiobook_maker_v3.0\audio_book_app.py", line 751, in generate_audio_for_sentence_threaded
    audio_path = self.generate_audio(sentence)
  File "D:\AIVoice\audiobook_maker_v3.0\audio_book_app.py", line 790, in generate_audio
    audio_path = call_api(sentence, **parameters)
  File "D:\AIVoice\audiobook_maker_v3.0\runtime\lib\site-packages\tortoise_api\tortoise_api.py", line 69, in call_api
    raise Exception("API call failed after 3 attempts")
Exception: API call failed after 3 attempts
2024-06-15 08:55:47 | INFO | httpx | HTTP Request: GET http://localhost:7860/heartbeat/fd175f8f-9cb6-4cfe-8de5-a97116b4bf3d "HTTP/1.1 404 Not Found"
2024-06-15 08:55:50 | INFO | httpx | HTTP Request: GET http://localhost:7860/heartbeat/fd175f8f-9cb6-4cfe-8de5-a97116b4bf3d "HTTP/1.1 404 Not Found"
2024-06-15 08:55:52 | INFO | httpx | HTTP Request: GET http://localhost:7860/heartbeat/fd175f8f-9cb6-4cfe-8de5-a97116b4bf3d "HTTP/1.1 404 Not Found"
2024-06-15 08:55:54 | INFO | httpx | HTTP Request: GET http://localhost:7860/heartbeat/fd175f8f-9cb6-4cfe-8de5-a97116b4bf3d "HTTP/1.1 404 Not Found"
2024-06-15 08:55:56 | INFO | httpx | HTTP Request: GET http://localhost:7860/heartbeat/fd175f8f-9cb6-4cfe-8de5-a97116b4bf3d "HTTP/1.1 404 Not Found"
2024-06-15 08:55:58 | INFO | httpx | HTTP Request: GET http://localhost:7860/heartbeat/fd175f8f-9cb6-4cfe-8de5-a97116b4bf3d "HTTP/1.1 404 Not Found"
2024-06-15 08:56:00 | INFO | httpx | HTTP Request: GET http://localhost:7860/heartbeat/fd175f8f-9cb6-4cfe-8de5-a97116b4bf3d "HTTP/1.1 404 Not Found"
2024-06-15 08:56:02 | INFO | httpx | HTTP Request: GET http://localhost:7860/heartbeat/fd175f8f-9cb6-4cfe-8de5-a97116b4bf3d "HTTP/1.1 404 Not Found"
2024-06-15 08:56:04 | INFO | httpx | HTTP Request: GET http://localhost:7860/heartbeat/fd175f8f-9cb6-4cfe-8de5-a97116b4bf3d "HTTP/1.1 404 Not Found"

**Comment by Troyificus** [comment]
I'm getting the exact same issue.

C:\Users\Trism\audiobook_maker_v3.0>.\runtime\python.exe .\audio_book_app.py
2024-10-03 13:35:52 | INFO | rvc.configs.config | Found GPU NVIDIA GeForce GTX 1080 Ti, force to fp32
2024-10-03 13:36:15 | INFO | httpx | HTTP Request: GET http://localhost:7860/config "HTTP/1.1 200 OK"
2024-10-03 13:36:17 | INFO | httpx | HTTP Request: GET http://localhost:7860/info "HTTP/1.1 200 OK"
Parameters being sent to Gradio app:
delimiter:

emotion: None
custom_emotion:
voice_name: Jonathon Keeble
microphone_source: None
voice_chunks: 0
candidates: 1
seed: 0
samples: 4
iterations: 32
temperature: 0.8
diffusion_sampler: DDIM
pause_size: 8
cvvp_weight: 0
top_p: 0.8
diffusion_temp: 1
length_penalty: 6
repetition_penalty: 6
conditioning_free_k: 2
experimental_flags: ['Half Precision', 'Conditioning-Free']
2024-10-03 13:36:17 | INFO | httpx | HTTP Request: POST http://localhost:7860/queue/join "HTTP/1.1 200 OK"
2024-10-03 13:36:18 | INFO | httpx | HTTP Request: GET http://localhost:7860/queue/data?session_hash=a7bae4b5-b15a-4d4a-b3af-b16423137623 "HTTP/1.1 200 OK"
2024-10-03 13:36:19 | INFO | httpx | HTTP Request: GET http://localhost:7860/heartbeat/a7bae4b5-b15a-4d4a-b3af-b16423137623 "HTTP/1.1 404 Not Found"
2024-10-03 13:36:21 | INFO | httpx | HTTP Request: GET http://localhost:7860/heartbeat/a7bae4b5-b15a-4d4a-b3af-b16423137623 "HTTP/1.1 404 Not Found"
2024-10-03 13:36:23 | INFO | httpx | HTTP Request: GET http://localhost:7860/heartbeat/a7bae4b5-b15a-4d4a-b3af-b16423137623 "HTTP/1.1 404 Not Found"
2024-10-03 13:36:25 | INFO | httpx | HTTP Request: GET http://localhost:7860/heartbeat/a7bae4b5-b15a-4d4a-b3af-b16423137623 "HTTP/1.1 404 Not Found"
2024-10-03 13:36:28 | INFO | httpx | HTTP Request: GET http://localhost:7860/heartbeat/a7bae4b5-b15a-4d4a-b3af-b16423137623 "HTTP/1.1 404 Not Found"
Error: 'rvc_model', retrying... (1/3)
2024-10-03 13:36:30 | INFO | httpx | HTTP Request: GET http://localhost:7860/heartbeat/a7bae4b5-b15a-4d4a-b3af-b16423137623 "HTTP/1.1 404 Not Found"
2024-10-03 13:36:32 | INFO | httpx | HTTP Request: GET http://localhost:7860/heartbeat/a7bae4b5-b15a-4d4a-b3af-b16423137623 "HTTP/1.1 404 Not Found"
Error: [WinError 10061] No connection could be made because the target machine actively refused it, retrying... (2/3)
2024-10-03 13:36:34 | INFO | httpx | HTTP Request: GET http://localhost:7860/heartbeat/a7bae4b5-b15a-4d4a-b3af-b16423137623 "HTTP/1.1 404 Not Found"
2024-10-03 13:36:36 | INFO | httpx | HTTP Request: GET http://localhost:7860/heartbeat/a7bae4b5-b15a-4d4a-b3af-b16423137623 "HTTP/1.1 404 Not Found"
Error: [WinError 10061] No connection could be made because the target machine actively refused it, retrying... (3/3)
Traceback (most recent call last):
  File "C:\Users\Trism\audiobook_maker_v3.0\audio_book_app.py", line 46, in run
    self.function(self.directory_path, self.report_progress)
  File "C:\Users\Trism\audiobook_maker_v3.0\audio_book_app.py", line 751, in generate_audio_for_sentence_threaded
    audio_path = self.generate_audio(sentence)
  File "C:\Users\Trism\audiobook_maker_v3.0\audio_book_app.py", line 789, in generate_audio
    audio_path = call_api(sentence, **parameters)
  File "C:\Users\Trism\audiobook_maker_v3.0\runtime\lib\site-packages\tortoise_api\tortoise_api.py", line 69, in call_api
    raise Exception("API call failed after 3 attempts")
Exception: API call failed after 3 attempts
2024-10-03 13:36:38 | INFO | httpx | HTTP Request: GET http://localhost:7860/heartbeat/a7bae4b5-b15a-4d4a-b3af-b16423137623 "HTTP/1.1 404 Not Found"
2024-10-03 13:36:40 | INFO | httpx | HTTP Request: GET http://localhost:7860/heartbeat/a7bae4b5-b15a-4d4a-b3af-b16423137623 "HTTP/1.1 404 Not Found"
2024-10-03 13:36:42 | INFO | httpx | HTTP Request: GET http://localhost:7860/heartbeat/a7bae4b5-b15a-4d4a-b3af-b16423137623 "HTTP/1.1 404 Not Found"
2024-10-03 13:36:44 | INFO | httpx | HTTP Request: GET http://localhost:7860/heartbeat/a7bae4b5-b15a-4d4a-b3af-b16423137623 "HTTP/1.1 404 Not Found"
2024-10-03 13:36:46 | INFO | httpx | HTTP Request: GET http://localhost:7860/heartbeat/a7bae4b5-b15a-4d4a-b3af-b16423137623 "HTTP/1.1 404 Not Found"
2024-10-03 13:36:48 | INFO | httpx | HTTP Request: GET http://localhost:7860/heartbeat/a7bae4b5-b15a-4d4a-b3af-b16423137623 "HTTP/1.1 404 Not Found"
2024-10-03 13:36:50 | INFO | httpx | HTTP Request: GET http://localhost:7860/heartbeat/a7bae4b5-b15a-4d4a-b3af-b16423137623 "HTTP/1.1 404 Not Found"
2024-10-03 13:36:52 | INFO | httpx | HTTP Request: GET http://localhost:7860/heartbeat/a7bae4b5-b15a-4d4a-b3af-b16423137623 "HTTP/1.1 404 Not Found"

_ad infinitum_

**Comment by JarodMica** [comment]
Version 3 is being changed up a lot, requests will not be required. Please wait for the status update on this project, which will be announced on the YouTube channel
