### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'configs/32k.json'

### ISSUE THREAD

**Issue by MJAnderson1** [JarodMica/audiobook_maker#6]
Trying to get it to work since yesterday but i keep getting the following error after which the GUI disappears ,Error : Calling API with sentence: <Lost and penniless, those few words were all he could think of..>
API response received with audio path: C:\Users\X\ai-voice-cloning\results/MYvoice//MYvoice_00009.wav
16系/10系显卡和P40强制单精度
Traceback (most recent call last):
  File "C:\Users\X\audiobook_maker\audio_book_app_2_0.py", line 29, in run
    self.function(self.directory_path, sentence, idx)
  File "C:\Users\x\audiobook_maker\audio_book_app_2_0.py", line 200, in 
generate_audio_for_sentence_threaded
    audio_path = self.generate_audio(sentence)
  File "C:\Users\x\audiobook_maker\audio_book_app_2_0.py", line 193, in 
generate_audio
    audio_path = rvc_convert(model_path=voice_model_path, resample_sr=0, input_path=audio_path)
  File "c:\users\X\audiobook_maker\venv\src\rvc-tts-pipe\rvc_infer.py", 
line 330, in rvc_convert
    config=Config(device,is_half)
  File "c:\users\X\audiobook_maker\venv\src\rvc-tts-pipe\rvc_infer.py", 
line 28, in _init_
    self.x_pad, self.x_query, self.x_center, self.x_max = self.device_config()
  File "c:\users\X\audiobook_maker\venv\src\rvc-tts-pipe\rvc_infer.py", 
line 44, in device_config
    with open(f"configs/{config_file}", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'configs/32k.json' please help

plus i don't seem to get the one with index

**Comment by JarodMica** [comment]
Can you pull the repository to get the latest update, this is the one with the index.

You can do this by opening a cmd window in the audiobook directory and doing ```git pull```

As well, there seems to be an issue with your RVC installation, so do the installation steps again.

It would be helpful if you list your hardware and system too.

**Comment by MJAnderson1** [comment]
I have a i5 10nth gen processor with a 1070 plus 16g ram , i already have rvc and tortoise installed and they are working perfectly, I aslo have all pre-requisites installed, my error always starts like this even after reinstaling rvc from the repository.

Warning: QT_DEVICE_PIXEL_RATIO is deprecated. Instead use:
   QT_AUTO_SCREEN_SCALE_FACTOR to enable platform plugin controlled per-screen factors.     
   QT_SCREEN_SCALE_FACTORS to set per-screen DPI.
   QT_SCALE_FACTOR to set the application global scale factor.
qt.qpa.fonts: Unable to open default EUDC font: "EUDC.TTE"
2023-09-27T11:49:35.301ZE [17060:ShellIpcClient] shell_ipc_client.cc:138:Connect Can't connect to socket at: \\.\Pipe\GoogleDriveFSPipe_userx_shell
2023-09-27T11:49:35.305ZE [17060:ShellIpcClient] shell_ipc_client.cc:621:operator() Failed to connect to the server: NOT_FOUND: Can't connect to socket at: \\.\Pipe\GoogleDriveFSPipe_userx_shell [type.googleapis.com/drive.ds.Status='UNAVAILABLE_RESOURCE']
=== Source Location Trace: ===
apps/drive/fs/ipc/shell_ipc_client.cc:139

2023-09-27T11:49:35.320ZE [14796:ShellIpcClient] shell_ipc_client.cc:138:Connect Can't connect to socket at: \\.\Pipe\GoogleDriveFSPipe_userx_shell
2023-09-27T11:49:35.320ZE [14796:ShellIpcClient] shell_ipc_client.cc:621:operator() Failed to connect to the server: NOT_FOUND: Can't connect to socket at: \\.\Pipe\GoogleDriveFSPipe_userx_shell [type.googleapis.com/drive.ds.Status='UNAVAILABLE_RESOURCE']
=== Source Location Trace: ===
apps/drive/fs/ipc/shell_ipc_client.cc:139

2023-09-27T11:49:35.321ZE [2216:ShellIpcClient] shell_ipc_client.cc:138:Connect Can't connect to socket at: \\.\Pipe\GoogleDriveFSPipe_userx_shell
2023-09-27T11:49:35.321ZE [2216:ShellIpcClient] shell_ipc_client.cc:621:operator() Failed to connect to the server: NOT_FOUND: Can't connect to socket at: \\.\Pipe\GoogleDriveFSPipe_userx_shell [type.googleapis.com/drive.ds.Status='UNAVAILABLE_RESOURCE']
=== Source Location Trace: ===
apps/drive/fs/ipc/shell_ipc_client.cc:139

**Comment by JarodMica** [comment]
You seem to be having two separate issues here, one where it can't find configs and then the latest.  What system are you using (Windows, linux)?

Are you storing anything on a Google Drive folder or trying to grab data in one?  If so, try to move everything to a local hard drive and see if this resolves issues.

The original issue suggests that the RVC package was not installed in editable mode, rendering it not capable of finding the json files.  I'm reworking on the package to get this working correctly, so I won't spend too much time here trying to debug this issue unfortunately here rn.

**Comment by MJAnderson1** [comment]
I am using windows 10, I trained all my tortoise filles on a colap but moved them from my google drive to local tortoise training folder.  I think I will wait for the reworking. thanks for your everything.
