### ISSUE TITLE
Cannot download tortoise due to this cache error

### ISSUE THREAD

**Issue by brokenbulb8** [JarodMica/audiobook_maker#65]
Cannot download tortoise due to this error. Works perfectly fine with pyttx3. Included the whole output if conda affects it by some chance.
```C:\Users\"SomeUserName">conda activate P311

(P311) C:\Users\"SomeUserName">cd C:\Users\"SomeUserName"\audiobook_maker

(P311) C:\Users\"SomeUserName"\audiobook_maker>python -m venv .venv

(P311) C:\Users\"SomeUserName"\audiobook_maker>.venv\Scripts\activate

(.venv) (P311) C:\Users\"SomeUserName"\audiobook_maker>python src\controller.py
There was a problem when trying to write in your cache folder (C:\Users\"SomeUserName"/.cache\huggingface\hub). You should set the environment variable TRANSFORMERS_CACHE to a writable directory.
[2024-10-23 01:57:50,899] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
test.c
LINK : fatal error LNK1181: cannot open input file 'aio.lib'
test.c
LINK : fatal error LNK1181: cannot open input file 'cufile.lib'
W1023 01:57:56.430000 44000 torch\distributed\elastic\multiprocessing\redirects.py:27] NOTE: Redirects are currently not supported in Windows or MacOs.
Loading TorToiSe... (AR: None, diffusion: , vocoder: )
Hardware acceleration found: cuda
use_deepspeed api_debug True
C:\Users\"SomeUserName"\audiobook_maker\.venv\Lib\site-packages\huggingface_hub\file_download.py:797: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Error calling Python override of QThread::run(): Traceback (most recent call last):
  File "C:\Users\"SomeUserName"\audiobook_maker\src\controller.py", line 37, in run
    self.function(self.directory_path, self.is_continue, self.report_progress, self.sentence_generated_callback, self.should_stop)
  File "C:\Users\"SomeUserName"\audiobook_maker\src\model.py", line 260, in generate_audio_for_sentence_threaded
    self.load_selected_tts_engine(tts_engine_name, speaker_id, **speaker_settings)
  File "C:\Users\"SomeUserName"\audiobook_maker\src\model.py", line 205, in load_selected_tts_engine
    self.tts_engine = tts_engines.load_tts_engine(chosen_tts_engine, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\"SomeUserName"\audiobook_maker\src\tts_engines.py", line 80, in load_tts_engine
    raise e
  File "C:\Users\"SomeUserName"\audiobook_maker\src\tts_engines.py", line 72, in load_tts_engine
    return load_with_tortoise(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\"SomeUserName"\audiobook_maker\src\tts_engines.py", line 118, in load_with_tortoise
    tts = load_tortoise_engine(
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\"SomeUserName"\audiobook_maker\.venv\Lib\site-packages\tortoise_tts_api\inference\load.py", line 38, in load_tts
    tts = TorToise_TTS(
          ^^^^^^^^^^^^^
  File "C:\Users\"SomeUserName"\audiobook_maker\.venv\Lib\site-packages\tortoise\api.py", line 298, in __init__
    self.aligner = Wav2VecAlignment(device='cpu' if get_device_name() == "dml" else self.device)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\"SomeUserName"\audiobook_maker\.venv\Lib\site-packages\tortoise\utils\wav2vec_alignment.py", line 58, in __init__
    self.model = Wav2Vec2ForCTC.from_pretrained("jbetker/wav2vec2-large-robust-ft-libritts-voxpopuli").cpu()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\"SomeUserName"\audiobook_maker\.venv\Lib\site-packages\transformers\modeling_utils.py", line 2251, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\"SomeUserName"\audiobook_maker\.venv\Lib\site-packages\transformers\configuration_utils.py", line 547, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\"SomeUserName"\audiobook_maker\.venv\Lib\site-packages\transformers\configuration_utils.py", line 574, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\"SomeUserName"\audiobook_maker\.venv\Lib\site-packages\transformers\configuration_utils.py", line 629, in _get_config_dict
    resolved_config_file = cached_file(
                           ^^^^^^^^^^^^
  File "C:\Users\"SomeUserName"\audiobook_maker\.venv\Lib\site-packages\transformers\utils\hub.py", line 417, in cached_file
    resolved_file = hf_hub_download(
                    ^^^^^^^^^^^^^^^^
  File "C:\Users\"SomeUserName"\audiobook_maker\.venv\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\"SomeUserName"\audiobook_maker\.venv\Lib\site-packages\huggingface_hub\file_download.py", line 862, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\"SomeUserName"\audiobook_maker\.venv\Lib\site-packages\huggingface_hub\file_download.py", line 979, in _hf_hub_download_to_cache_dir
    os.makedirs(os.path.dirname(blob_path), exist_ok=True)
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 225, in makedirs
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\"SomeUserName"/.cache\\huggingface'```

**Comment by JarodMica** [comment]
I'm not entirely sure what may have occured for why your system isn't able to download from huggingface, though it shouldn't be trying to download to .cache location, it should be looking to download in the models directory for tortoise 

Can you try and delete maybe the huggingface folder at the .cache directory? If you have other hugging face models in there, you might just wanna look for a folder from jbetcker and delete that in there
