### ISSUE TITLE
Voices with styletts2

### ISSUE THREAD

**Issue by danielw97** [JarodMica/audiobook_maker#83]
Hi there,
This looks like a very useful tool, thanks for your work.
one issue I'm running into is that following the manual installation method when trying to start out using styletts2, there appear to be no voices that are selectable.
I have placed several wav files in the voices\styletts directory, and I can select those under the voice reference file combobox.
However, they dont' appear to be selectable under the voice combobox itself.

Not sure if that makes sense, are there aditional steps I have to take in order to select a voice?
Currently if I try to start generation when just selecting a voice reference file I receive this error:
Error calling Python override of QThread::run(): Traceback (most recent call last):                                     
  File "C:\Users\daniel\Documents\audiobook_maker\src\controller.py", line 48, in run                                   
    self.function(self.directory_path, self.is_continue, self.report_progress, self.sentence_generated_callback, self.should_stop)                                                                                                              
  File "C:\Users\daniel\Documents\audiobook_maker\src\model.py", line 284, in generate_audio_for_sentence_threaded      
    audio_path = self.generate_audio_proxy(sentence, speaker_settings, s2s_validated)                                   
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                   
  File "C:\Users\daniel\Documents\audiobook_maker\src\model.py", line 310, in generate_audio_proxy                      
    success = tts_engines.generate_audio(self.tts_engine, sentence, voice_parameters, tts_engine_name, audio_path)      
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^      
  File "C:\Users\daniel\Documents\audiobook_maker\src\tts_engines.py", line 27, in generate_audio                       
    return generate_with_styletts2(tts_engine, sentence, voice_parameters, audio_path)                                  
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                  
  File "C:\Users\daniel\Documents\audiobook_maker\src\tts_engines.py", line 64, in generate_with_styletts2              
    raise ("No voice found for StyleTTS")                                                                               
TypeError: exceptions must derive from BaseException                                                                    
 Thanks in advance for any help with this.

**Comment by danielw97** [comment]
Solved by watching your most recent video where you demonstrate this.
